stages:   
   - quality
   - build
   - unit_test
   - active_tests

variables:
  GIT_STRATEGY: clone
  TIMEOUT: 10m

styleCheck:
   stage: quality
   script:
      - make style

build:
   stage: build
   tags:
      - "docker"
   script:
      - make docker
      